# This is a basic workflow to help you get started with Actions

name: build_client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ client ]
  pull_request:
    branches: [ client ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: client
          
      # Install SDL
      - name: install sdl
        run: sudo apt-get update && sudo apt-get install libsdl2-dev
        
      # Go to client and make
      - name: Go to client and make
        run: cd $GITHUB_WORKSPACE/src/client && make
        
      # Upload the build artifact
      - name: Upload the build artifact
        run: ls
